services:
  app:
    build: .
    container_name: recipick-app
    restart: always
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: ${sist_url}
      SPRING_DATASOURCE_USERNAME: ${sist_username}
      SPRING_DATASOURCE_PASSWORD: ${sist_password}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.driver.OracleDriver
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_AI_GOOGLE_GENAI_API_KEY: ${GEN_KEY}

      sist_url: ${sist_url}
      sist_username: ${sist_username}
      sist_password: ${sist_password}

      sist_post_url: ${sist_post_url}
      post_username: ${post_username}
      post_password: ${post_password}

      jwt_secret: ${jwt_secret}
      GEN_KEY: ${GEN_KEY}
      IMG_KEY: ${IMG_KEY}
      social_key: ${social_key}
      mail_username: ${mail_username}
      mail_password: ${mail_password}
    expose:
      - "8080"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: recipick-redis
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  redis-data: